Task.find_or_create_by(title: 'Таск 1')
Task.find_or_create_by(title: 'Таск 2')
Task.find_or_create_by(title: 'Таск 3', is_done: true)
Task.find_or_create_by(title: 'Таск 4')
Task.find_or_create_by(title: 'Таск 5')